@host=https://localhost:7047
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTY0NjY0Mi1mYmEzLTQ0OGUtOWYxYy1jMTYyNjc1ODA4Y2QiLCJnaXZlbl9uYW1lIjoidGVzdCIsImZhbWlseV9uYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdCIsImp0aSI6ImUwZWYyYzA1LTI0Y2YtNDU5NC04YTA1LWNmMjBjMTM4OTc4NSIsIm5iZiI6MTY3ODIzNjQzOCwiZXhwIjoxNjc4MjM4MjM4LCJpc3MiOiJBZGRyZXNzQm9vayIsImF1ZCI6IkFkZHJlc3NCb29rIn0.D15Y_Q6fSr8otV5iihrXCSuHAQIzDPIV7Z8MU5OB3YI
GET {{host}}/contacts/get-all
Content-Type: application/json
Authorization: Bearer {{token}}